export const sigAlgs = [
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsapss',
    hashFunction: 'sha256',
    domainParameter: '3',
    keyLength: '4096',
    checkNullifier: true,
  },
  {
    dgHashAlgo: 'sha1',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsa',
    hashFunction: 'sha256',
    domainParameter: '65537',
    keyLength: '2048',
    checkNullifier: true,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha224',
    sigAlg: 'ecdsa',
    hashFunction: 'sha224',
    domainParameter: 'brainpoolP224r1',
    keyLength: '224',
    checkNullifier: true,
  },
];

export const fullSigAlgs = [
  {
    dgHashAlgo: 'sha1',
    eContentHashAlgo: 'sha1',
    sigAlg: 'ecdsa',
    hashFunction: 'sha1',
    domainParameter: 'secp256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha512',
    eContentHashAlgo: 'sha512',
    sigAlg: 'rsa',
    hashFunction: 'sha512',
    domainParameter: '65537',
    keyLength: '4096',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha1',
    eContentHashAlgo: 'sha1',
    sigAlg: 'rsa',
    hashFunction: 'sha1',
    domainParameter: '65537',
    keyLength: '2048',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsa',
    hashFunction: 'sha256',
    domainParameter: '65537',
    keyLength: '2048',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsapss',
    hashFunction: 'sha256',
    domainParameter: '65537',
    keyLength: '2048',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsapss',
    hashFunction: 'sha256',
    domainParameter: '65537',
    keyLength: '3072',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsapss',
    hashFunction: 'sha256',
    domainParameter: '65537',
    keyLength: '4096',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsapss',
    hashFunction: 'sha256',
    domainParameter: '3',
    keyLength: '4096',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsapss',
    hashFunction: 'sha256',
    domainParameter: '3',
    keyLength: '3072',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsa',
    hashFunction: 'sha256',
    domainParameter: '3',
    keyLength: '2048',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'rsa',
    hashFunction: 'sha256',
    domainParameter: '65537',
    keyLength: '3072',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'ecdsa',
    hashFunction: 'sha256',
    domainParameter: 'secp256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha1',
    eContentHashAlgo: 'sha1',
    sigAlg: 'ecdsa',
    hashFunction: 'sha1',
    domainParameter: 'secp256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'ecdsa',
    hashFunction: 'sha256',
    domainParameter: 'brainpoolP256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'ecdsa',
    hashFunction: 'sha256',
    domainParameter: 'secp384r1',
    keyLength: '384',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha384',
    eContentHashAlgo: 'sha384',
    sigAlg: 'ecdsa',
    hashFunction: 'sha384',
    domainParameter: 'brainpoolP256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha384',
    eContentHashAlgo: 'sha384',
    sigAlg: 'ecdsa',
    hashFunction: 'sha384',
    domainParameter: 'brainpoolP384r1',
    keyLength: '384',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha384',
    eContentHashAlgo: 'sha384',
    sigAlg: 'ecdsa',
    hashFunction: 'sha384',
    domainParameter: 'secp384r1',
    keyLength: '384',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha512',
    eContentHashAlgo: 'sha512',
    sigAlg: 'ecdsa',
    hashFunction: 'sha512',
    domainParameter: 'brainpoolP256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha224',
    sigAlg: 'ecdsa',
    hashFunction: 'sha224',
    domainParameter: 'brainpoolP224r1',
    keyLength: '224',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'ecdsa',
    hashFunction: 'sha256',
    domainParameter: 'brainpoolP224r1',
    keyLength: '224',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha1',
    eContentHashAlgo: 'sha1',
    sigAlg: 'ecdsa',
    hashFunction: 'sha1',
    domainParameter: 'brainpoolP224r1',
    keyLength: '224',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha256',
    eContentHashAlgo: 'sha256',
    sigAlg: 'ecdsa',
    hashFunction: 'sha256',
    domainParameter: 'secp256r1',
    keyLength: '256',
    checkNullifier: false,
  },
  {
    dgHashAlgo: 'sha512',
    eContentHashAlgo: 'sha512',
    sigAlg: 'ecdsa',
    hashFunction: 'sha512',
    domainParameter: 'brainpoolP512r1',
    keyLength: '512',
    checkNullifier: false,
  },
];
