// Constant Values in OneTimeSBT.sol
export const ATTRIBUTE_ISSUING_STATE_INDEX = 0;
export const ATTRIBUTE_NAME_INDEX = 1;
export const ATTRIBUTE_PASSPORT_NUMBER_INDEX = 2;
export const ATTRIBUTE_NATIONALITY_INDEX = 3;
export const ATTRIBUTE_DATE_OF_BIRTH_INDEX = 4;
export const ATTRIBUTE_GENDER_INDEX = 5;
export const ATTRIBUTE_EXPIRY_DATE_INDEX = 6;
export const ATTRIBUTE_OLDER_THAN_INDEX = 7;

export const PROVE_RSA_NULLIFIER_INDEX = 0;
export const PROVE_RSA_REVEALED_DATA_PACKED_INDEX = 1;
export const PROVE_RSA_OLDER_THAN_INDEX = 4;
export const PROVE_RSA_PUBKEY_DISCLOSED_INDEX = 6;
export const PROVE_RSA_FORBIDDEN_COUNTRIES_LIST_PACKED_DISCLOSED_INDEX = 38;
export const PROVE_RSA_OFAC_RESULT_INDEX = 40;
export const PROVE_RSA_COMMITMENT_INDEX = 41;
export const PROVE_RSA_BLINDED_DSC_COMMITMENT_INDEX = 42;
export const PROVE_RSA_CURRENT_DATE_INDEX = 43;
export const PROVE_RSA_USER_IDENTIFIER_INDEX = 49;
export const PROVE_RSA_SCOPE_INDEX = 50;

export const DSC_BLINDED_DSC_COMMITMENT_INDEX = 0;
export const DSC_MERKLE_ROOT_INDEX = 1;

// Enum in VerifiersManager.sol
export const VERIFICATION_TYPE_ENUM_PROVE = 0;
export const VERIFICATION_TYPE_ENUM_DSC = 1;
