//SPDX-License-Identifier: MIT
pragma solidity ^0.8.18;

uint256 constant ATTRIBUTE_ISSUING_STATE_INDEX = 0;
uint256 constant ATTRIBUTE_NAME_INDEX = 1;
uint256 constant ATTRIBUTE_PASSPORT_NUMBER_INDEX = 2;
uint256 constant ATTRIBUTE_NATIONALITY_INDEX = 3;
uint256 constant ATTRIBUTE_DATE_OF_BIRTH_INDEX = 4;
uint256 constant ATTRIBUTE_GENDER_INDEX = 5;
uint256 constant ATTRIBUTE_EXPIRY_DATE_INDEX = 6;
uint256 constant ATTRIBUTE_OLDER_THAN_INDEX = 7;

uint256 constant PROVE_RSA_NULLIFIER_INDEX = 0;
uint256 constant PROVE_RSA_REVEALED_DATA_PACKED_INDEX = 1;
uint256 constant PROVE_RSA_OLDER_THAN_INDEX = 4;
uint256 constant PROVE_RSA_PUBKEY_DISCLOSED_INDEX = 6;
uint256 constant PROVE_RSA_FORBIDDEN_COUNTRIES_LIST_PACKED_DISCLOSED_INDEX = 38;
uint256 constant PROVE_RSA_OFAC_RESULT_INDEX = 40;
uint256 constant PROVE_RSA_COMMITMENT_INDEX = 41;
uint256 constant PROVE_RSA_BLINDED_DSC_COMMITMENT_INDEX = 42;
uint256 constant PROVE_RSA_CURRENT_DATE_INDEX = 43;
uint256 constant PROVE_RSA_USER_IDENTIFIER_INDEX = 49;
uint256 constant PROVE_RSA_SCOPE_INDEX = 50;

uint256 constant DSC_BLINDED_DSC_COMMITMENT_INDEX = 0;