// use dep::bignum::BigNum;
// use dep::bignum::runtime_bignum::BigNumInstance;
// use dep::std;

// use dep::rsa::types::{RSA, RSA2048, BN2048, BNInst2048};

// pub fn rsa_signature_verifier(bn: [[Field; 18]; 2], hash: [u8; 32], signature: BN2048) {
//     let rsa: RSA2048 = RSA {};
//     let BNInstance: BNInst2048 = BigNumInstance::new(bn[0], bn[1]);
//     assert(rsa.verify_sha256_pkcs1v15(BNInstance, hash, signature, 65537));
// }

