export const ProofSteps = {
    WAITING_FOR_MOBILE: 'WAITING_FOR_MOBILE',
    MOBILE_CONNECTED: 'MOBILE_CONNECTED',
    PROOF_GENERATION_STARTED: 'PROOF_GENERATION_STARTED',
    PROOF_GENERATED: 'PROOF_GENERATED',
    PROOF_VERIFIED: 'PROOF_VERIFIED'
};