export const ATTESTATION_ID = {
    E_PASSPORT: "0x12d57183e0a41615471a14e5a93c87b9db757118c1d7a6a9f73106819d656f24"
}

export const CONTRACT_CONSTANTS = {
    REGISTER_NULLIFIER_INDEX: 0,
    REGISTER_COMMITMENT_INDEX: 1,
    REGISTER_BLINDED_DSC_COMMITMENT_INDEX: 2,

    DSC_BLINDED_DSC_COMMITMENT_INDEX: 0,
    DSC_CSCA_ROOT_INDEX: 1,

    VC_AND_DISCLOSE_NULLIFIER_INDEX: 0,
    VC_AND_DISCLOSE_REVEALED_DATA_PACKED_INDEX: 1,
    VC_AND_DISCLOSE_OLDER_THAN_INDEX: 4,
    VC_AND_DISCLOSE_FORBIDDEN_COUNTRIES_LIST_PACKED_DISCLOSED_INDEX: 6,
    VC_AND_DISCLOSE_OFAC_RESULT_INDEX: 8,
    VC_AND_DISCLOSE_ATTESTATION_ID_INDEX: 9,
    VC_AND_DISCLOSE_CURRENT_DATE_INDEX: 10,
    VC_AND_DISCLOSE_USER_IDENTIFIER_INDEX: 16,
    VC_AND_DISCLOSE_SCOPE_INDEX: 17,
    VC_AND_DISCLOSE_SMT_ROOT_INDEX: 18,
    VC_AND_DISCLOSE_MERKLE_ROOT_INDEX: 19,
}